backend:
  name: git-gateway
  branch: master

display_url: https://covenantchristianwv.com

media_folder: static/img
public_folder: /img

collections:
  - name: "home"
    label: "Home"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Meta Description, name: description, widget: string}
          - {label: YouTube Video ID, name: youtubeId, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/util/navigation.md"
        label: "Navigation"
        name: "navigation"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "utility"}
          - {label: "Title", name: "title", widget: "hidden",  default: "navigation"}
          - {
            label: Navigation,
            name: navigation,
            label_singular: Menu,
            widget: list,
            fields:
              [
                {
                  label: Menu,
                  name: menu,
                  label_singular: Item,
                  widget: list,
                  fields:
                    [
                      { label: Title, name: title, widget: string },
                      {
                        label: Page URL,
                        name: pageUrl,
                        widget: relation,
                        collection: pages,
                        searchFields: ["title", "slug"],
                        valueField: title,
                        required: false,
                        hint: "Either a Page URL or an “Other URL” can be used, but *not* both.",
                      },
                      { label: Other URL, name: externalUrl, widget: string, required: false },
                      { label: Open in New Tab, name: openInNewTab, widget: boolean, required: false }
                    ]
                },
              ],
          }

  - name: pages
    label: Pages
    label_singular: Page
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    filter: {field: "templateKey", value: "content-page"}
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "blog"
    label: Blog
    label_singular: Blog Post
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
